name: keywordschat
description: Simple conversational keyword research tool
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.1
  flutter_markdown: ^0.7.4+1
  fl_chart: ^0.65.0
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

